### ISSUE TITLE
Crash in settings 

### ISSUE THREAD

**Issue by ThatOneCalculator** [Goooler/LawnchairRelease#42]
This doesn't occur in the 14-dev debug build. 

```
Lawnchair bug report Dec 22, 2023 8:56:13 AM
version: 14.0.0 (edc256e) (14000000)
commit: edc256e
build.brand: google
build.device: panther
build.display: UQ1A.231205.015.2023121200
build.fingerprint: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
build.hardware: panther
build.id: UQ1A.231205.015
build.manufacturer: Google
build.model: Pixel 7
build.security.level: 2023-12-05
build.product: panther
build.type: user
version.codename: REL
version.incremental: 2023121200
version.release: 14
version.sdk_int: 34
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair/app.lawnchair.LawnchairLauncher}: java.lang.ClassCastException: androidx.activity.l cannot be cast to com.android.launcher3.Launcher$NonConfigInstance
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3813)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3953)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5983)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5879)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:64)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5943)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.ClassCastException: androidx.activity.l cannot be cast to com.android.launcher3.Launcher$NonConfigInstance
	at com.android.launcher3.Launcher.restoreState(Unknown Source:23)
	at com.android.launcher3.Launcher.onCreate(Unknown Source:251)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(Unknown Source:0)
	at app.lawnchair.LawnchairLauncher.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:8677)
	at android.app.Activity.performCreate(Activity.java:8655)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3795)
	... 19 more

```

**Comment by ThatOneCalculator** [comment]
It seems to be related to the Device Search experimental feature

**Comment by Goooler** [comment]
Fixed! Thanks for this reporting.

**Comment by ThatOneCalculator** [comment]
Thank you so much for the quick fix! Can confirm it works normally now.
