### ISSUE TITLE
ShortCut support

### ISSUE THREAD

**Issue by Rw-Ro** [Goooler/LawnchairRelease#48]
It is not support Shortcut now.

**Comment by Goooler** [comment]
Crashing like this?

```
Lawnchair bug report 2024年1月28日 13:29:29
version: 14.0.0 (c69b652) (14000000)
commit: c69b652
build.brand: motorola
build.device: rtwo
build.display: U1TR34.8-19-11
build.fingerprint: motorola/rtwo_cn/rtwo:14/U1TR34.8-19-11/a7b98-bf32f9:user/release-keys
build.hardware: qcom
build.id: U1TR34.8-19-11
build.manufacturer: motorola
build.model: XT2301-5
build.security.level: 2024-01-01
build.product: rtwo_cn
build.type: user
version.codename: REL
version.incremental: a7b98-bf32f9
version.release: 14
version.sdk_int: 34
display.density_dpi: 446
isRecentsEnabled: true

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.dragndrop.DragView.animateShift(int, int)' on a null object reference
	at com.android.launcher3.popup.PopupContainerWithArrow$LauncherPopupItemDragHandler.onLongClick(Unknown Source:109)
	at android.view.View.performLongClickInternal(View.java:7766)
	at android.view.View.performLongClick(View.java:7722)
	at android.widget.TextView.performLongClick(TextView.java:14676)
	at android.view.View.performLongClick(View.java:7740)
	at android.view.View$CheckForLongPress.run(View.java:30302)
	at android.os.Handler.handleCallback(Handler.java:1000)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
```

**Comment by Goooler** [comment]
Try out the build artifact from https://github.com/Goooler/LawnchairRelease/actions/runs/7684377704
