### ISSUE TITLE
[BUG] QuickSteps crashs

### ISSUE THREAD

**Issue by DylanAkp** [Goooler/LawnchairRelease#58]
### Describe the bug

When Quickstep from lawnchair is used, and another launcher is set as the default one, gestures won't work and lawnchair will crash, here is a crashlog of the issue

```
Lawnchair bug report 12 mars 2024 20:47:18
version: 14.0.0 (3f516c2) (14000000)
commit: 3f516c2
build.brand: Nothing
build.device: Pong
build.display: UKQ1.240201.001 release-keys
build.fingerprint: Nothing/Pong/Pong:14/UKQ1.240201.001/eng.dylana.20240312.152743:userdebug/release-keys
build.hardware: qcom
build.id: UKQ1.240201.001
build.manufacturer: Nothing
build.model: A065
build.security.level: 2024-02-05
build.product: Pong
build.type: userdebug
version.codename: REL
version.incremental: eng.dylana.20240312.152743
version.release: 14
version.sdk_int: 34
display.density_dpi: 420
isRecentsEnabled: true

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair/com.android.quickstep.RecentsActivity}: android.view.InflateException: Binary XML file line #53 in app.lawnchair:layout/fallback_recents_activity: Binary XML file line #22 in app.lawnchair:layout/overview_actions_container: Error inflating class app.lawnchair.overview.LawnchairOverviewActionsView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3823)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3964)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: android.view.InflateException: Binary XML file line #53 in app.lawnchair:layout/fallback_recents_activity: Binary XML file line #22 in app.lawnchair:layout/overview_actions_container: Error inflating class app.lawnchair.overview.LawnchairOverviewActionsView
Caused by: android.view.InflateException: Binary XML file line #22 in app.lawnchair:layout/overview_actions_container: Error inflating class app.lawnchair.overview.LawnchairOverviewActionsView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:871)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1253)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1139)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1146)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(Unknown Source:5)
	at com.android.quickstep.RecentsActivity.setupViews(Unknown Source:2)
	at com.android.quickstep.RecentsActivity.onCreate(Unknown Source:15)
	at android.app.Activity.performCreate(Activity.java:8621)
	at android.app.Activity.performCreate(Activity.java:8599)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1460)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3805)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3964)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: java.lang.ClassCastException: com.android.quickstep.RecentsActivity cannot be cast to app.lawnchair.LawnchairLauncher
	at bb.a.V1(Unknown Source:14)
	at app.lawnchair.overview.LawnchairOverviewActionsView.<init>(SourceFile:4)
	at app.lawnchair.overview.LawnchairOverviewActionsView.<init>(SourceFile:1)
	... 31 more
```

Since the issue won't appear on Goooler/LawnchairRelease@043f02d release but only on Goooler/LawnchairRelease@3f516c2, I guess this is related to the commit bfb4ddf with the compat lib

**Comment by DylanAkp** [comment]
It also seems that Goooler/LawnchairRelease@043f02d's Quickswitch make the keyboard freeze when switching between 2 apps using the keyboard, sadly, can't found any logs for that
So the latest fully working QuickSwitch without noticeable issue is the release Goooler/LawnchairRelease@54f1767

**Comment by Goooler** [comment]
Which QS version you are using?

**Comment by DylanAkp** [comment]
I'm not using QuickSwitch, I built the OS directly with your lawnchair release prebuilts and lawnchair set as the default quickstep

**Comment by Goooler** [comment]
This might be fixed by https://github.com/LawnchairLauncher/lawnchair/commit/e0727ec9b0a0c2eaf61cfb49643717b4ef51ec68, can you try with the latest build from https://github.com/Goooler/LawnchairRelease/actions/runs/8305649228?

**Comment by DylanAkp** [comment]
At least, the crash is fixed, but the keyboard and gestures still freeze suddenly while switching apps

**Comment by Goooler** [comment]
Please check if the same issue is presented in the upstream repository. If so, please file the issue to that repository instead.
