### ISSUE TITLE
[BUG] Crash when trying to change home screen grid

### ISSUE THREAD

**Issue by omer-1080314** [Goooler/LawnchairRelease#63]
### Describe the bug

```Lawnchair bug report 24 Mar 2024 02:11:03
version: 14.0.0 (fc07992) (14000000)
commit: fc07992
build.brand: realme
build.device: RE5C33
build.display: RMX3823_14.0.0.211(CN01)
build.fingerprint: realme/RMX3823/RE5C33:14/UKQ1.230924.001/T.168aae2-4af5-f2652:user/release-keys
build.hardware: qcom
build.id: UKQ1.230924.001
build.manufacturer: realme
build.model: RMX3823
build.security.level: 2024-02-05
build.product: RMX3823
build.type: user
version.codename: REL
version.incremental: T.168aae2-4af5-f2652
version.release: 14
version.sdk_int: 34
display.density_dpi: 476
isRecentsEnabled: true

error: Uncaught exception

java.lang.SecurityException: Op READ_MEDIA_IMAGES ignore for package app.lawnchair
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
	at android.os.Parcel.createException(Parcel.java:3071)
	at android.os.Parcel.readException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:2996)
	at android.app.IWallpaperManager$Stub$Proxy.getWallpaperWithFeature(IWallpaperManager.java:1011)
	at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:793)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:683)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:632)
	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1041)
	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1003)
	at w6.f1.invokeSuspend(Unknown Source:7)
	at wa.a.resumeWith(Unknown Source:8)
	at sb.l0.run(Unknown Source:114)
	at m.j.run(Unknown Source:31)
	at yb.k.run(Unknown Source:2)
	at yb.c.l(Unknown Source:0)
	at yb.a.run(Unknown Source:97)
	Suppressed: xb.g: [z1.p2@89cc1da, q0.i@66b260b, u1{Cancelling}@8b8bce8, n1@3a74f01]
Caused by: android.os.RemoteException: Remote stack trace:
	at android.os.storage.StorageManager.noteAppOpAllowingLegacy(StorageManager.java:1870)
	at android.os.storage.StorageManager.checkPermissionReadImages(StorageManager.java:1899)
	at com.android.server.wallpaper.WallpaperManagerService.getWallpaperWithFeature(WallpaperManagerService.java:3153)
	at android.app.IWallpaperManager$Stub.onTransact(IWallpaperManager.java:537)
	at android.os.Binder.execTransactInternal(Binder.java:1387)```

**Comment by Goooler** [comment]
```
java.lang.SecurityException: Op READ_MEDIA_IMAGES ignore for package app.lawnchair
  at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
  at android.os.Parcel.createException(Parcel.java:3071)
  at android.os.Parcel.readException(Parcel.java:3054)
  at android.os.Parcel.readException(Parcel.java:2996)
  at android.app.IWallpaperManager$Stub$Proxy.getWallpaperWithFeature(IWallpaperManager.java:1011)
  at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:793)
  at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:683)
  at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:632)
  at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1041)
  at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1003)
  at app.lawnchair.ui.preferences.components.WallpaperPreviewKt$wallpaperDrawable$wallpaperDrawable$2$1.invokeSuspend(Unknown Source:7)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
  at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
  at androidx.appcompat.widget.ActionMenuPresenter$OpenOverflowRunnable.kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:31)
  at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:97)
```

**Comment by Goooler** [comment]
I can't repro.

[Screen_recording_20240324_173645.webm](https://github.com/Goooler/LawnchairRelease/assets/10363352/685ff6ab-9e02-483b-9eda-10abc30d9e36)

**Comment by omer-1080314** [comment]
https://github.com/Goooler/LawnchairRelease/assets/144014913/be53ace0-56e9-498b-b41e-bf27f4983b1a

**Comment by Goooler** [comment]
I guess this could be reproduced on the latest build artifact in the upstream repo, if so, file an issue to it.
